---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags:
        - always
    - name: Set ansible_distribution to Ubuntu
      set_fact: ansible_distribution="Ubuntu"
      tags:
        - always

  roles:
    - role: darkwizard242.googlechrome
      when: install_chrome
      become: true
      tags:
        - chrome
    - role: geerlingguy.docker
      when: install_docker
      become: true
      tags:
        - docker
    - role: webarchitect609.jet_brains_toolbox
      when: install_jetbrains_toolbox
      become: true
      tags:
        - jetbrains_toolbox
    - role: ngetchell.vscode
      when: install_vscode
      become: true
      tags:
        - vscode

  tasks:
    - name: Install ZSH
      import_tasks: tasks/zsh.yml
      when: install_zsh
      become: true
      tags:
        - zsh

    - name: Install NVM
      import_tasks: tasks/nvm.yml
      when: install_nvm
      tags:
        - node
        - nvm

    - name: Install AWS Cli
      import_tasks: tasks/awscli.yml
      when: install_aws
      become: true
      tags:
        - awscli

    - name: Install Spotify
      import_tasks: tasks/spotify.yml
      when: install_spotify
      tags:
        - spotify
    
    - name: Install GitHub Desktop
      import_tasks: tasks/github-desktop.yml
      when: install_github_desktop
      tags:
        - github

    - name: Install Krita
      import_tasks: tasks/krita.yml
      when: install_krita
      tags:
        - krita

    - name: Install Zoom
      import_tasks: tasks/zoom.yml
      when: install_zoom
      tags:
        - zoom

    - name: Install Bitwarden
      import_tasks: tasks/bitwarden.yml
      when: install_bitwarden
      tags:
        - bitwarden

    - name: Install Oh My ZSH
      import_tasks: tasks/ohmyzsh.yml
      when: install_ohmyzsh
      tags:
        - ohmyzsh

    - name: Set .zshrc
      import_tasks: tasks/zshrc.yml
      when: configure_zshrc
      tags:
        - zshrc

    - name: Install camset
      import_tasks: tasks/camset.yml
      when: install_camset
      become: true
      tags:
        - camset

    - name: Install invoke
      import_tasks: tasks/invoke.yml
      when: install_invoke
      become: true
      tags:
        - invoke

    - name: Set hardware clock to local timezone
      import_tasks: tasks/hwclock.yml
      when: hw_clock_local_timezone
      tags:
        - hwclock
